vmware_web_service.gemspec

Remove manageiq-gems-pending from gemspec

---

.rubocop_local.yml

Add a minimum ruby target version to rubocop_local.yml

Add a minimum ruby target version to rubocop

---

lib/VMwareWebService/MiqVimHost.rb
lib/VMwareWebService/MiqVimVm.rb
lib/VMwareWebService/exception.rb
lib/VMwareWebService/miq_fault_tolerant_vim.rb
spec/VMwareWebService/MiqVimVm_spec.rb

Move all VMware related exceptions from gems-pending util/miq-exception
into VMwareWebService/exception

Move exceptions from util/miq-exception

---

lib/VMwareWebService/DMiqVimSync.rb

Add diagnostic code to dump out the buffer and object sent from the broker if either the DRbMessage size or Marshal version are invalid.
Some errors which have been seen are:
```
Error: [incompatible marshal file format (can't be read)
format version 4.8 required; 0.0 given] 
[----] E, [2017-07-13T16:51:38.667163 #28357:a4798c] ERROR -- : Q-task_id([miq_provision_509000000041948]) /opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/core_ext/marshal.rb:4:in `load' 
/opt/rh/cfme-gemset/gems/activesupport-5.0.0.1/lib/active_support/core_ext/marshal.rb:4:in `load' 
/var/www/miq/vmdb/config/initializers/marshal_autoloader.rb:3:in `load' 
/opt/rh/rh-ruby22/root/usr/share/ruby/drb/drb.rb:593:in `block in load'
/opt/rh/rh-ruby22/root/usr/share/ruby/sync.rb:233:in `block in …
```

Add marshal version and DRb message size checks

---

vmware_web_service.gemspec

For https://github.com/ManageIQ/manageiq/issues/15036

Allow Rails 5.1

---

lib/VMwareWebService/MiqVimVm.rb

PR to support resize disk from reconfigure screen
See: https://github.com/ManageIQ/manageiq-ui-classic/issues/3127

Add resize disk to reconfigure screen

---

Gemfile
test/VixDiskLib/rawTest.rb
vmware_web_service.gemspec

Switch to use the extracted manageiq-password gem.

Switch to manageiq-password from gems-pending

---

vmware_web_service.gemspec

This reverts commit cf35230b875bd68e05c2889e52cb6684114241e1, reversing changes made to 77ea0f8275d91d12677b15d30aef107ed424c5d6.
* * *
My previous witty PR titles and commit messages probably made this PR inevitable...

Revert "Merge pull request #49 from NickLaMuro/an_optimistic_update"

---

Gemfile
test/VixDiskLib/rawTest.rb

@agrare @jrafanie Please review.

Remove references to MiqPassword

---

lib/VMwareWebService/MiqVimInventory.rb
lib/VMwareWebService/VimPropMaps.rb
lib/VMwareWebService/VimService.rb

vSphere 5.0 was released in 2011, think we can drop code supporting 2.x
and 4.x

Think it is safe to depend on vSphere 5.0 minimum

---

lib/VMwareWebService/MiqVimInventory.rb
lib/VMwareWebService/MiqVimObjectSet.rb

ESX hosts don't have License or ExtensionManagers
https://bugzilla.redhat.com/show_bug.cgi?id=1730805

Don't use License or Extension Managers on hosts

---

lib/VMwareWebService/wsdl41/vimws25MappingRegistry.rb

Related to https://github.com/ManageIQ/manageiq-providers-vmware/pull/458/files
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1754665

NSX network support

---

lib/VMwareWebService/VimPropMaps.rb

Be able to report if a VM has BIOS or EFI firmware type

Collect VirtualMachine config.firmware

---

lib/VMwareWebService/MiqVimVm.rb

There are methods to add and remove disks but no method to resize an existing disk.
https://github.com/ManageIQ/manageiq-providers-vmware/issues/524

Add a method to resize a disk via ReconfigVm_Task

---

lib/VMwareWebService/MiqVimCustomizationSpecManager.rb
lib/VMwareWebService/MiqVimVm.rb

Reuse the same array rather than creating a new one

Prefer Array.wrap over #to_miq_a

---

lib/VMwareWebService/MiqVim.rb

Missed this when cleaning up https://github.com/ManageIQ/vmware_web_service/pull/85

Fix pbm_initialize which should have beeen removed

---

lib/VMwareWebService/MiqVimEventMonitor.rb
lib/VMwareWebService/MiqVimHost.rb
lib/VMwareWebService/MiqVimInventory.rb
lib/VMwareWebService/MiqVimVm.rb
test/VMwareWebService/MiqVimPerfTest.rb
test/VMwareWebService/diskPerf.rb
test/VMwareWebService/rtPerfTest.rb
test/VMwareWebService/vdlBrowserTest.rb
test/VMwareWebService/virtualDiskPerf.rb
test/VixDiskLib/cookedTest.rb

I also don't think we need these

remove superfluous requires part two

---

.rubocop_local.yml

@agrare Please review - this should get rid of the warnings in the PRs.

Qualify Style/GlobalVars cop

---

lib/VMwareWebService/MiqVim.rb
lib/VMwareWebService/MiqVimClientBase.rb
lib/VMwareWebService/MiqVimEventMonitor.rb
lib/VMwareWebService/MiqVimInventory.rb

```
openssl genrsa -des3 -out ca.key 2048
openssl req -x509 -new -nodes -key ca.key -sha256 -days 1000 -out ca.crt
openssl genrsa -out vcsim.key 2048
openssl req -new -key vcsim.key -out vcsim.csr
openssl x509 -req -in vcsim.csr -CA ca.crt -CAkey ca.key -C -out vcsim.crt -days 1000 -sha256 -CAcreateserial
go/bin/vcsim -tlscert vcsim.crt -tlskey vcsim.key
```

Add support for verify_mode and ca_file

---

.github/workflows/ci.yaml
Gemfile
spec/spec_helper.rb
vmware_web_service.gemspec

* Allow rails 6.1
* Test multiple rails versions with github actions.
Note, we're trying to simplify this by not using appraisals and this PR demonstrates how simple it can be.

Allow rails 6.1

---

lib/VMwareWebService/VixDiskLib/vdl_wrapper.rb
lib/VMwareWebService/logging.rb

Fix a few issues with logging from the VixDiskLibServer which is run as a separate process
https://github.com/ManageIQ/manageiq-providers-vmware/issues/858

Fix VixDiskLibServer logging

---

Gemfile

reference https://rubygems.manageiq.org

---

vmware_web_service.gemspec

@agrare Please review. This should get rid of the Mend Bolt issues.

Bump manageiq-style for rexml CVEs

---

vmware_web_service.gemspec

Update manageiq-style to latest

Update manageiq-style to latest
