ManageIQ/vmware_web_service

lib/VMwareWebService/MiqVimHost.rb
lib/VMwareWebService/MiqVimVm.rb
test/VMwareWebService/emsRefreshTest.rb
vmware_web_service.gemspec

A number of files were requiring util/miq-hash but not using any methods
directly.  Replace with more_core_extensions/core_ext/hash.

Remove dependency on miq-hash from gems-pending

---

lib/VMwareWebService/MiqVimDataStore.rb
test/VMwareWebService/browserTest.rb

The getFs() method in `MiqVimDataStore` was only called by `test/browserTest.rb` but was requiring a dependency on `MiqFS` from `manageiq-gems-pending`.  Move the method and requires over to the test file.

Move MiqFS dependency to the test file

---

lib/VMwareWebService/VixDiskLib/VixDiskLibServer.rb
lib/VMwareWebService/VixDiskLib/vdl_wrapper.rb

VixDiskLibServer was requiring log4r but not using it.

Remove log4r from VixDiskLibServer

---

vmware_web_service.gemspec

httpclient is on `v2.8.3` now so bump the dependency.
Depends on: https://github.com/ManageIQ/manageiq-gems-pending/pull/180

Bump httpclient to ~>2.8.0

---

lib/VMwareWebService/MiqVimDataStore.rb

Retrieving a file from a datastore by connecting through a host was
failing due to an SSL certificate error.

Fix getting file content from a datastore

---

test/VMwareWebService/emsRefreshTest.rb

Since requiring `util/vmdb-logger` from `manageiq-gems-pending` is not really necessary for the `emsRefreshTest.rb`, use the vanilla ruby Logger instead.  This removes it from being needed entirely in this repo.
QA
--
Not sure myself how this script is run/used, but I am not sure if it is covered in the tests, so it most likely should be tested with this change in place to see if it causes issues, or works just fine.

Remove util/vmdb-logger as a dependency

---

vmware_web_service.gemspec

Update the RbVmomi gem after https://github.com/vmware/rbvmomi/pull/114 fixed the issue https://github.com/vmware/rbvmomi/issues/113 causing storage policy based management to fail.

Update RbVmomi gem after PBM fix

---

lib/vmware_web_service.rb

This moves the eager loading of VimTypes.rb in ManageIQ found
[here](https://github.com/ManageIQ/manageiq/blob/93eb4c0afd3c62f43dce86630dd453295300451c/lib/vmdb/initializer.rb#L6-L7)
to this repo.  We eager loaded this file previously in the main repo for two reasons:
1) VimHash, VimArray, etc. objects could be serialized in the miq_queue table
2) VimTypes.rb doesn't follow rails autoload patterns so rails cannot autoload this file when those constants are encountered
Instead, we can autoload VimTypes when these constants are needed.

Autoload the various VimTypes

---

lib/VMwareWebService/MiqVimPerfHistory.rb

There are two options for format for the PerfQuery method, normal and
csv.  Allow the caller to specifiy which format they want instead of
forcing normal.

Allow callers to override format for PerfQuery

---

lib/VMwareWebService/MiqVimBroker.rb
lib/VMwareWebService/MiqVimDrbDebug.rb

Add client side DrbMessage#load checks

---

vmware_web_service.gemspec

Update ffi-vix_disk_lib to fix a segfault in libvixDiskLib version 6.5
while connecting to a host.
Fixed by: https://github.com/ManageIQ/ffi-vix_disk_lib/pull/11
https://bugzilla.redhat.com/show_bug.cgi?id=1527658

Update ffi-vix_disk_lib to fix segfault

---

lib/VMwareWebService/MiqVimVm.rb

This PR adds the method `getDeviceKeysByLabel` to retrieve the network adapters device keys for the given network adapter label. This method is part of the new functionality added to the Reconfigure VM webpage.
This PR is part of a set of PRs:
https://github.com/ManageIQ/vmware_web_service/pull/25
https://github.com/ManageIQ/manageiq-providers-vmware/pull/163
https://github.com/ManageIQ/manageiq/pull/16700
https://github.com/ManageIQ/manageiq-ui-classic/pull/3121
More info: https://github.com/ManageIQ/manageiq-ui-classic/issues/3119

Reconfigure VM: Add / Remove Network Adapters

---

lib/VMwareWebService/MiqPbmInventory.rb

The SPBM endpoint isn't exposed by ESX hosts, only VIM.  Trying to
connect to SPBM on a Host resulted in the following warning:
`WARN -- : MiqPbmInventory: Failed to connect to SPBM endpoint: ERROR: Undefined namespace prefix: //soapenv:Body/*`

Fix SPBM connect error when connecting to a Host

---

lib/VMwareWebService/MiqVimEventMonitor.rb
lib/VMwareWebService/VimPropMaps.rb

When a VM is disconnected the VM's UUID is the only property which can
be used to link the VM to other entities e.g. events.
https://bugzilla.redhat.com/show_bug.cgi?id=1538996

Add VM UUID to event payload

---

lib/VMwareWebService/MiqVimVm.rb

Log snapshot ref to warn on creation and deletion to ensure that it makes it to the vim.log
https://bugzilla.redhat.com/show_bug.cgi?id=1549299

Enhance logging around snapshot create/delete

---

lib/VMwareWebService/miq_fault_tolerant_vim.rb

Switch to ems.hostname instead.

The use of ems.address is deprecated

---

lib/VMwareWebService/MiqVimBroker.rb

Incrase the DRb::DRbServer.load_limit to 100MiB to handler larger vSphere inventories.
https://bugzilla.redhat.com/show_bug.cgi?id=1573588

Increase the DRb::DRbServer.load_limit size from 50 to 100 MiB

---

lib/VMwareWebService/VimPropMaps.rb

Collect config.uuid in addition to summary.config.uuid for cases when
the later is null.
https://bugzilla.redhat.com/show_bug.cgi?id=1569090

Add VirtualMachine config.uuid to VimPropMaps

---

lib/VMwareWebService/MiqVimVm.rb

Add a method to return a VirtualDevice by label and refactor the
existing getDeviceKeysByLabel to use it.
https://bugzilla.redhat.com/show_bug.cgi?id=1533728

Add a getDeviceByLabel method

---

vmware_web_service.gemspec

RbVmomi released version 1.12.0 to add support for vSphere 6.7

Bump version of the rbvmomi gem to 1.12.0

---

vmware_web_service.gemspec

Pull in https://github.com/vmware/rbvmomi/pull/138 to fix issues parsing
host virtual switch and portgroups.

Bump rbvmomi version to 1.13.0

---

lib/VMwareWebService/MiqVimVm.rb
lib/VMwareWebService/VimService.rb

Add the ability to rename a VM from the MiqVimVm object.
VIM SDK definition: https://www.vmware.com/support/developer/vc-sdk/visdk41pubs/ApiReference/vim.ManagedEntity.html#rename
https://bugzilla.redhat.com/show_bug.cgi?id=1559184

Add MiqVimVm#renameVM method

---

lib/VMwareWebService/MiqVimBroker.rb
lib/VMwareWebService/miq_fault_tolerant_vim.rb

Switch from using a normal TCP socket to a UNIX socket file and change
the file permissions to 0750 to prevent unprivileged users from being
able to access it.
CVE Number: CVE-2018-10905
https://bugzilla.redhat.com/show_bug.cgi?id=1599389

Use a UNIX socket for the DRb server

---

vmware_web_service.gemspec

ffi-vix_disk_lib 1.0.5, implemented via https://github.com/ManageIQ/ffi-vix_disk_lib/pull/13 
adds support for VmWare vddk 6.7.
@roliveri @agrare please review and merge (although I believe @agrare is indisposed for some number of days at the moment)
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1651702

Update ffi-vix_disk_lib to 1.0.5

---

lib/VMwareWebService/VimPropMaps.rb

We were collecting the vmFolder, datastoreFolder, and hostFolder...all
except the networkFolder.  For consistency with streaming/graph refresh
we should collect the networkFolder.

Collect the networkFolder under a Datacenter

---

vmware_web_service.gemspec

VMware released an update for 6.7u1, https://github.com/vmware/rbvmomi/releases/tag/v2.1.0

Bump rbvmomi to 2.1.0

---

lib/VMwareWebService/VimPropMaps.rb

NSX networks are represented in the VIM sdk as a different
network/switch type.  Add the Opaque Network/Switch details to the
VimPropMaps for a HostSystem.
https://github.com/ManageIQ/manageiq-providers-vmware/issues/397

Add Host OpaqueNetwork/Switch to VimPropMaps

---

lib/VMwareWebService/MiqVimInventory.rb
lib/VMwareWebService/VimPropMaps.rb

If we try to collect inventory from the host the collection fails because
hosts don't have the extensionManager or licenseManager.
Depends on: https://github.com/ManageIQ/vmware_web_service/pull/60

Fix an issue connecting to a host directly

---

lib/VMwareWebService/wsdl41/methods/VirtualMachineRelocateSpecDiskLocator.yml
lib/VMwareWebService/wsdl41/vimws25MappingRegistry.rb

the relocate spec needs the backing info property so we can do Lazy Zeroed and Eager Zeroed thick provisioning
part of work for https://bugzilla.redhat.com/show_bug.cgi?id=1633867 
Related to https://github.com/ManageIQ/manageiq-providers-vmware/pull/413 and 
https://github.com/ManageIQ/manageiq-providers-vmware/pull/385

relocate_spec_disk_locator needs diskBackingInfo

---

.travis.yml
vmware_web_service.gemspec

manageiq-gems-pending dropped support for 2.3 here https://github.com/ManageIQ/manageiq-gems-pending/pull/440
Ruby 2.3 was last used on gaprindashvilli which uses vmware_web_service 0.3.3 and this is on 0.4.z

Drop ruby 2.3 and add ruby 2.5 support

---

Gemfile
lib/VMwareWebService/broker_timeout.rb
spec/VMwareWebService/broker_timeout_spec.rb

Replace `ExitException` with `Timeout::Error`
`ExitException` was removed in ruby 2.2

Correct broker_timeout error class

---

lib/VMwareWebService/DMiqVim.rb
lib/VMwareWebService/MiqVim.rb

Now that some of the previous "broker" functionality is being run not
over DRb but from a shared session in a worker we need to be able to run
the monitor updates thread which keeps the inventory cache up to date
from MiqVim not just DMiqVim.
DMiqVim still has some extra logic specifically in error handling that
is specific to being run from within the broker so some of that is still
needed in DMiqVim but the bulk of it can move to MiqVim.

Allow running the monitorUpdates thread in MiqVim

---

vmware_web_service.gemspec

Allow updating to the most recent version of RbVmomi (2.3.0)

Relax the dependency on rbvmomi

---

lib/VMwareWebService/VimTypes.rb

Ruby 2.6 introduced a Hash#filter method which breaks the event catcher since it calls `#filter` on the PropertyFilterUpdate
https://github.com/ManageIQ/vmware_web_service/blob/master/lib/VMwareWebService/MiqVimEventMonitor.rb#L57

Undefine Hash#filter in VimHash, used by event catcher

---

lib/VMwareWebService/MiqVimEventMonitor.rb

It has been seen that the vm["uuid"] property can be {} which later
breaks database queries trying to cast VimHash to a string.
https://github.com/ManageIQ/manageiq-providers-vmware/issues/420

Prevent possible empty hash in vm["uuid"] field

---

lib/VMwareWebService/MiqVimDataStore.rb
lib/VMwareWebService/MiqVimUpdate.rb
lib/VMwareWebService/MiqVimVm.rb

This fixes a series of warnings that you'll see when running the smartstate specs. Specifically:
```
lib/VMwareWebService/MiqVimVm.rb:336: warning: mismatched indentations at 'end' with 'begin' at 319
lib/VMwareWebService/MiqVimVm.rb:807: warning: mismatched indentations at 'end' with 'begin' at 802
lib/VMwareWebService/MiqVimVm.rb:863: warning: mismatched indentations at 'end' with 'begin' at 858
lib/VMwareWebService/MiqVimVm.rb:1057: warning: mismatched indentations at 'end' with 'begin' at 1039
lib/VMwareWebService/MiqVimVm.rb:90: warning: method redefined; discarding old vmMor
lib/VMwareWebService/MiqVimVm.rb:94: warning: method redefined; discarding old vmh
lib/VMwareWebService/MiqVimDataStore.rb:293: warning: assigned but unused variable - meta …
```

Warning fixes

---

vmware_web_service.gemspec

more core ext's on 4.1.0
update for update sake
https://github.com/ManageIQ/more_core_extensions/compare/179bf40..e5b4501
- Added Ruby 2.7 support [[#79](https://github.com/ManageIQ/more_core_extensions/pull/79)]
- Added Process#pause, Process#resume, and Process#alive? [[#73](https://github.com/ManageIQ/more_core_extensions/pull/73)]
array added * `#compact_map` - Collect non-nil results from the block
array added `#tabular_sort` - Sorts an Array of Hashes by specific columns
hierarchy added `#descendant_get` - Returns the descendant with a given name
the two breaking changes:
- **BREAKING**: Moved Object#descendant_get to Class#descendant_get [[#75](https://github.com/ManageIQ/more_core_extensions/pull/75)]
- **BREAKING**: Removed deprecated Enumerable#stable_sort_by …

bump more core extensions

---

lib/VMwareWebService/MiqVimInventory.rb

Followup to https://github.com/ManageIQ/vmware_web_service/pull/81, looks like I missed one.
This is just an indentation warning that cropped up when running the specs locally for smartstate.

Fix indentation in MiqVimInventory.rb

---

vmware_web_service.gemspec

Fixed in ActiveSupport 5.2.4.3
https://hakiri.io/github/ManageIQ/vmware_web_service/master/7436ee8637b89780c4b66debba4ca63c16c8df94/warnings?name=Code+Injection
Ivanchuk uses vmware_web_service v0.4* so we wont break the ivanchuk branch with this change and jansa already uses rails 5.2.4.3

Fix code injection vulnerability in activesupport

---

lib/VMwareWebService/MiqVimInventory.rb

The createTime format returned by the vCenter API is iso8601 but doesn't pad 0s out to the decimal precision like Time#iso8601 does.
This means that if there is a trailing 0 for the createTime getSnapMor won't find the snapshot and snap deletes and reverts will fail.
https://github.com/ManageIQ/manageiq-providers-vmware/issues/631

Ensure snapshot createTime format matches refresh

---

lib/VMwareWebService/MiqVimInventory.rb

Ensure snapshot createTime format matches refresh
(cherry picked from commit c03d082989578389d2c4b8a9308c05141856b1bb)

[v1.0.z] Backport of "Merge pull request #87 from agrare/fix_snapshot_timestamp_lookup"

---

lib/VMwareWebService/MiqVimCustomizationSpecManager.rb
lib/VMwareWebService/MiqVimVm.rb

When gems-pending removed to_miq_a we also lost the implicit `require 'active_support/core_ext/array/wrap'`
https://github.com/ManageIQ/manageiq-gems-pending/pull/489

Fix Array.wrap failure after gems-pending update

---

lib/VMwareWebService/MiqVim.rb

Allow for subsequent connections to share the same monitor_updates/pre_load options as set by a worker.  This mirrors how the old Broker would maintain connection settings set by the worker across connection instances.

Add MiqVim class-level options for monitor_updates/pre_load

---

.travis.yml
vmware_web_service.gemspec

Travis is failing on ruby 2.4: https://travis-ci.com/github/ManageIQ/vmware_web_service/jobs/471939906
```
Bundler could not find compatible versions for gem "ruby":
In Gemfile:
ruby
manageiq-gems-pending (> 0) was resolved to 0.1.0, which depends on
activesupport (~> 6.0) was resolved to 6.1.1, which depends on
ruby (>= 2.5.0)
vmware_web_service was resolved to 2.1.0, which depends on
ruby (> 2.4)
```

Rails 6 doesn't support ruby 2.4

---

test/VixDiskLib/rawTest.rb

These were added in manageiq@59c362337639422376967bfa405c08e2baf02390 to
debug some encryption issues.  Safe to say it is no longer an issue.

Remove useless encryption/decryption tests

---

vmware_web_service.gemspec

https://github.com/ManageIQ/vmware_web_service/pull/104 removed the only usage of ManageIQ::Password so this gem can be dropped now from the gemspec

Drop the manageiq-password dependency

---

lib/VMwareWebService/VixDiskLib/VixDiskLib.rb
lib/VMwareWebService/VixDiskLib/VixDiskLibServer.rb
lib/VMwareWebService/VixDiskLib/vdl_wrapper.rb

When we spawn we're already setting `:out` to the file, so logging to stdout in the child process would have gone to the log file anyway.  In addition to this use the parent process's $stdout

Use $stdout in VixDiskLibServer for logging

---

.github/workflows/ci.yaml

- Move ENV vars to global list
- Ensure code climate only runs on 1 job

Cleanup for consistency

---

.github/workflows/ci.yaml
vmware_web_service.gemspec

Current versions of nokogiri require ruby 2.6 at a minimum.  Drop ruby 2.5 support.

Drop ruby 2.5 support

---

lib/VMwareWebService/VixDiskLib/VixDiskLib.rb
lib/VMwareWebService/logging.rb

The VixDiskLib.connect method is a class-method and the `VMwareWebService::Logging` module only defined an instance method.
```
ERROR -- evm: Q-task_id([job_dispatcher]) Unable to mount filesystem.  Reason:[undefined local variable or method `logger' for VixDiskLib:Class] for VM [[88888-INFRA02-NFS4IO] 88888-egMGRtest-TUSA/88888-egMGRtest-TUSA.vmx]
ERROR -- evm: Q-task_id([job_dispatcher]) MIQExtract.new /opt/manageiq/manageiq-gemset/gems/vmware_web_service-3.1.0/lib/VMwareWebService/VixDiskLib/VixDiskLib.rb:102:in `setup_env'
ERROR -- evm: Q-task_id([job_dispatcher]) MIQExtract.new /opt/manageiq/manageiq-gemset/gems/vmware_web_service-3.1.0/lib/VMwareWebService/VixDiskLib/VixDiskLib.rb:112:in `start_service'
ERROR -- evm: Q-task_id([job_dispatcher]) MIQExtract.new …
```

Fix undefined method logger in VixDiskLib.connect

---

.github/workflows/ci.yaml
lib/VMwareWebService/MiqVimDataStore.rb

Update the ruby version matrix to include 3.0 which shows a failure using `URI.encode` in the `MiqVimDataStore` class

Update ruby versions used to run CI
